version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: lara-app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        networks:
            - lara
        environment:
            APP_ENV: local
            APP_DEBUG: "true"

    nginx:
        image: nginx:stable
        container_name: lara-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        networks:
            - lara

    mysql:
        image: mysql:8.0
        container_name: lara-mysql
        restart: unless-stopped
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - lara
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lara
            MYSQL_USER: lara
            MYSQL_PASSWORD: asdf

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: lara-phpmyadmin
        restart: unless-stopped
        ports:
            - "8081:80" # Access phpMyAdmin at http://localhost:8081
        environment:
            PMA_HOST: lara-mysql # The hostname of the MySQL service
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        networks:
            - lara

    mailhog:
        image: mailhog/mailhog
        container_name: lara-mailhog
        restart: unless-stopped
        ports:
            - "8025:8025" # Access MailHog web UI at http://localhost:8025
            - "1025:1025" # SMTP port
        networks:
            - lara

volumes:
    db_data:

networks:
    lara:
